import turtle as trt
import runnng_square as RS
import mink_curve as MC
import levi as LV
import koch as KC
import ice_fract_1 as IF1
import ice_fract_2 as IF2
import carpet as CR
import branch as BR
import bin_tree as BT
import H_fractale as H
import vicsek as VC
import ru_local as RU


def print_menu() -> None:
    """
        Display the fractal selection menu to the user.

        Shows the main menu title and lists all available fractal types
        that can be generated by the program.
        """
    print(RU.MENU)
    print(RU.AVAILABLE_FRACTALES)


def available_fractales(
        size: int, depth: int, angle: int,
        koef: float, total: int, x: float, y: float,
        width: int, height: int
) -> dict:
    """
        Create a dictionary mapping fractal IDs to their drawing functions.

        Args:
            size (int): Base size/length for the fractal
            depth (int): Recursion depth for fractal generation
            angle (int): Angle parameter for certain fractals
            koef (float): Coefficient parameter for scaling
            total (int): Total number of segments/iterations
            x (float): X-coordinate starting position
            y (float): Y-coordinate starting position
            width (int): Width parameter for H-fractal
            height (int): Height parameter for H-fractal

        Returns:
            dict: Dictionary where keys are fractal IDs and values are
                  callable functions that generate the corresponding fractals
        """
    fractales = {
        1: lambda: RS.running_sq(size, angle, koef, depth),
        2: lambda: BT.tree(size, depth, total),
        3: lambda: BR.branch(depth, size, total),
        4: lambda: KC.koch(size, depth, total),
        5: lambda: KC.snowflake(size, depth, total),
        6: lambda: MC.mink_curve(depth, size, total),
        7: lambda: IF1.ice_fract(depth, size, total),
        8: lambda: IF2.ice_fract_2(depth, size, total),
        9: lambda: LV.levi(size, depth, total),
        10: lambda: CR.sierpinski_carpet(x, y, size, depth, total),
        11: lambda: H.H_recursive(x, y, width, height, depth, 0, total),
        12: lambda: VC.vicsek(x, y, size, depth, total)
    }
    return fractales


def determine_total(choise: int, depth: int) -> int:
    """
       Calculate the total number of segments for a given fractal type and depth.

       Different fractal algorithms require different calculations for the total
       number of drawing segments based on recursion depth.

       Args:
           choise (int): Fractal type identifier (2-12)
           depth (int): Recursion depth for the fractal

       Returns:
           int: Total number of segments that will be drawn
       """
    totals = {
        2: BT.count_segments(depth),
        3: BR.count_branches(depth),
        4: KC.count_segments(depth),
        5: KC.count_segments(depth) * 3,
        6: MC.count_segments(depth),
        7: IF1.count_segments(depth),
        8: IF2.count_segments(depth),
        9: LV.count_segments(depth),
        10: CR.count_squares(depth),
        11: H.count_H_segments(depth),
        12: VC.count_squares(depth)
    }
    return totals[choise]


def main() -> None:
    """
       Main function to run the fractal drawing program.

       Handles user interaction, parameter collection, and initiates
       the selected fractal drawing. Manages the turtle graphics setup
       and provides a menu-driven interface for fractal selection.

       The function:
       1. Initializes default parameters
       2. Displays the selection menu
       3. Collects user input for fractal type and parameters
       4. Calculates appropriate totals for progress tracking
       5. Executes the selected fractal drawing function

       Uses turtle graphics for visualization with tracer disabled
       for improved drawing performance.
       """
    size = 0
    angle = 15
    koef = 0.15
    total = 10000
    x = 0
    y = 0
    width = 0
    height = 0

    print_menu()

    choise = None
    while choise not in range(1, 13):
        choise = int(input(RU.FRACT_NUMB))

    depth = int(input(RU.ENTER_DEPTH))

    if choise == 1:
        angle = int(input(RU.ENTER_ANGLE))
        koef = float(input(RU.ENTER_KOEF))

    if choise == 11:
        height = int(input(RU.ENTER_HEIGHT))
        width = int(input(RU.ENTER_WIDTH))
    else:
        size = int(input(RU.ENTER_SIZE))

    if 10 <= choise <= 12:
        x = int(input(RU.ENTER_X))
        y = int(input(RU.ENTER_Y))

    if choise != 1:
        total = determine_total(choise, depth)

    fractales = available_fractales(
        size, depth, angle,
        koef, total,
        x, y, width, height
    )

    func = fractales.get(choise)
    func()


if __name__ == '__main__':
    trt.tracer(False)
    main()
    trt.update()
    trt.done()
